[rhel_7_install_host_group]
manmrspot01.premiere.local
10.96.37.67
[anotherGROUP]
#host1
#host2

#[rhel_7_install_host_group:vars]
#//tsm_targetEnv=test_disk_dir o prod_disk_dir
#tsm_targetEnv=test_disk_dir
